name = "DHWGenerator"
uuid = "4867afc0-e43d-4d41-999a-a30083bc751e"
authors = ["Takuya Iwanaga","Chinenye Ani"]
version = "0.1.0"

[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeoIO = "f5a160d5-e41d-4189-8b61-d57781c419e3"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
GeometryOps = "3251bfac-6a57-4b6d-aa61-ac1fef2975ab"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
YAXArrays = "c21b50f5-aa40-41ea-b809-c0f5e47bfa5c"

[compat]
ArchGDAL = "0.10.10"
Conda = "1.10.2"
DataFrames = "1.8.0"
Distributions = "0.25.120"
GLMakie = "0.13.6"
GeoIO = "1.20.7"
GeoInterface = "1.6.0"
GeometryBasics = "0.5.10"
GeometryOps = "0.1.29"
NCDatasets = "0.14.8"
OrderedCollections = "1.8.1"
PyCall = "1.96.4"
